"""Results from seasons that predate the tracker.

ABR 14 was run on a spreadsheet, so there are no PlayerMatchup rows to
derive fantasy costs from. These win counts are transcribed from the
league's Individual Standings sheet, where every player's stated record
was checked against their round-by-round results before being copied here.

Names are as they appear in that sheet and are matched to tracker users
case-insensitively; anyone unmatched is treated as new to the league,
which is the same rule applied to a season the tracker does hold.
"""

# Season key -> {player name: matches won}
HISTORICAL_SEASON_WINS = {
    "abr14": {
        'architect': 3,
        'Arly': 4,
        'autro': 4,
        'AV8R': 5,
        'Bakermouse': 2,
        'Barlow': 3,
        'Barry_Skywalker374': 5,
        'Battell': 4,
        'BHawk': 4,
        'bigmackrorschach': 4,
        'BigZestEnergy': 3,
        'Brobnar89': 2,
        'Bumping': 4,
        'catsmdogs': 6,
        'Childboy': 2,
        'Contecaly': 3,
        'cptncrispy': 4,
        'DaPapa': 2,
        'davec': 5,
        'Dexter': 5,
        'Disthis': 4,
        'Dom Pham': 3,
        'donutsdad': 4,
        'DougS (DugT8r)': 2,
        'DragonMaster': 2,
        'Drazkor': 2,
        'Drsheep': 4,
        'Easygallina': 2,
        'Emperor riku': 7,
        'Ewok_jr': 2,
        'Fig': 3,
        'FlamingHobo': 4,
        'Foolishbigj': 3,
        'General_St0re': 3,
        'girltrumpeter85': 0,
        'Gorlami': 2,
        'GreenBeanCowboy': 2,
        'Grishhammer': 3,
        'Harmed': 5,
        'ianyoinc': 4,
        'ionprod': 3,
        'Jase': 4,
        'JDG314': 4,
        'JeffreyPP': 2,
        'Jennenn': 4,
        'JonBever': 6,
        'jtrussell': 5,
        'Juliejuly': 5,
        'Jupiter': 1,
        'Kalosianfire': 4,
        'kastravir': 3,
        'KellyPhi Dragon': 3,
        'King-of-Bling': 1,
        'Kirkman': 3,
        'logancomposer': 5,
        'logeyspark': 1,
        'Lqdsquash': 4,
        'magic_duck': 1,
        'MammonDG': 5,
        'Marty (Hasame180)': 4,
        'Matze51': 6,
        'MiBluffin': 3,
        'Miggy9001': 3,
        'Moosemandude': 4,
        'MoZi': 5,
        'Mrs.Pancake': 2,
        'mwb_24': 3,
        'nedmike': 5,
        'Nobe': 2,
        'not2night': 5,
        'notthebest95': 3,
        'Orbital Tangent': 3,
        'Orion0497': 3,
        'Player Hurp': 4,
        'PunchDeLeon': 4,
        'quickdraw3457': 4,
        'SCSteele': 4,
        'Shadowmeld': 3,
        'siaka': 5,
        'SithofAngmar': 2,
        'snek': 2,
        'Sofaltis': 4,
        'stormstrong': 3,
        'sushichef': 3,
        'Thytiom': 6,
        'trandinhkhang': 3,
        'Tron317': 5,
        'Tutenkharnage': 3,
        'UltimoFox': 3,
        'Varghast': 6,
        'vhorlon': 2,
        'Walaboo15': 3,
        'xjoaniex': 2,
        'xoque': 5,
        'xraycreator': 6,
        'Zenzizenzizenzic': 3,
    },
}

# Shown in the commissioner's cost-source picker.
HISTORICAL_SEASON_LABELS = {
    "abr14": "ABR 14 (from the league spreadsheet)",
}
